
Detect and remove outliers from a dataset using the Z-score method.


Import libraries

In [1]:
import numpy as np
from scipy import stats

Create dataset

In [2]:
arr = [10, 12, 11, 13, 12, 100, 11, 12, 13, 11]

Convert to array

In [3]:
data = np.array(arr)
data

array([ 10,  12,  11,  13,  12, 100,  11,  12,  13,  11])

Calculate Z-score

In [4]:
z_scores = np.abs(stats.zscore(data))
z_scores

array([0.39600092, 0.32057217, 0.35828654, 0.2828578 , 0.32057217,
       2.99829267, 0.35828654, 0.32057217, 0.2828578 , 0.35828654])

Detect outliers

In [5]:
outliers=z_scores > 2.5
outliers

array([False, False, False, False, False,  True, False, False, False,
       False])

Remove outliers

In [6]:
cleaned_data=data[~outliers]
cleaned_data

array([10, 12, 11, 13, 12, 11, 12, 13, 11])